Repository wal-g/wal-g, pull requests merged in 2023-08, with the labels that each got.

#1530 Dead lock fix
  internal/splitmerge/splitmerge_test.go
  internal/splitmerge/splitreader.go
  internal/stream_push_helper.go
  internal/stream_push_helper_test.go
  internal/testutils/s3_error_folder.go
Labels: bug, mysql, Mongo

#1533 MariaDB Test Fix
  Makefile
  docker/mariadb/Dockerfile
Labels: mysql

#1532 MongoDB binary restore: Added flag for particular replica set member ids
  cmd/mongo/binary_backup_fetch.go
  internal/databases/mongo/binary/mongod.go
  internal/databases/mongo/binary/mongod_test.go
  internal/databases/mongo/binary_backup_fetch_handler.go
Labels: Mongo
