Repository wal-g/wal-g, pull requests merged in 2025-01, with the labels that each got.

#1878 tests: remove few "sleep"
  docker/cloudberry_tests/scripts/tests/ao_storage_test.sh
  docker/cloudberry_tests/scripts/tests/ao_storage_without_metadata_test.sh
  docker/cloudberry_tests/scripts/tests/backup_after_failed_backup_test.sh
  docker/cloudberry_tests/scripts/tests/delete_before_name_test.sh
  docker/cloudberry_tests/scripts/tests/delete_before_permanent_test.sh
  docker/cloudberry_tests/scripts/tests/delete_before_time_test.sh
  docker/cloudberry_tests/scripts/tests/delete_garbage_test.sh
  docker/cloudberry_tests/scripts/tests/delete_retain_test.sh
  docker/cloudberry_tests/scripts/tests/delete_target_delta_find_full_test.sh
  docker/cloudberry_tests/scripts/tests/delete_target_delta_test.sh
  docker/cloudberry_tests/scripts/tests/delete_target_test.sh
  docker/cloudberry_tests/scripts/tests/delete_without_confirm_test.sh
  docker/cloudberry_tests/scripts/tests/delta_backup_test.sh
  docker/cloudberry_tests/scripts/tests/gp_full_backup_test.sh
  docker/cloudberry_tests/scripts/tests/partial_database_restore_test.sh
  docker/cloudberry_tests/scripts/tests/partial_namespace_restore.sh
  docker/cloudberry_tests/scripts/tests/partial_restore_wildcard.sh
  docker/cloudberry_tests/scripts/tests/partial_table_restore_test.sh
  docker/cloudberry_tests/scripts/tests/restore_point.sh
  docker/gp_tests/scripts/tests/ao_storage_test.sh
  docker/gp_tests/scripts/tests/ao_storage_without_metadata_test.sh
  docker/gp_tests/scripts/tests/backup_after_failed_backup_test.sh
  docker/gp_tests/scripts/tests/delete_before_name_test.sh
  docker/gp_tests/scripts/tests/delete_before_permanent_test.sh
  docker/gp_tests/scripts/tests/delete_before_time_test.sh
  docker/gp_tests/scripts/tests/delete_garbage_test.sh
  docker/gp_tests/scripts/tests/delete_retain_test.sh
  docker/gp_tests/scripts/tests/delete_target_delta_find_full_test.sh
  docker/gp_tests/scripts/tests/delete_target_delta_test.sh
  docker/gp_tests/scripts/tests/delete_target_test.sh
  docker/gp_tests/scripts/tests/delete_without_confirm_test.sh
  docker/gp_tests/scripts/tests/delta_backup_test.sh
  docker/gp_tests/scripts/tests/gp_full_backup_test.sh
  docker/gp_tests/scripts/tests/partial_database_restore_test.sh
  docker/gp_tests/scripts/tests/partial_namespace_restore.sh
  docker/gp_tests/scripts/tests/partial_restore_wildcard.sh
  docker/gp_tests/scripts/tests/partial_table_restore_test.sh
  docker/gp_tests/scripts/tests/restore_point.sh
Labels: Greenplum

#1879 Fix SIGSEGV errors of wal-g delete
  internal/delete_handler.go
Labels: postgres

#1880 WALG-1873. MySQL > use datadir as incremental dir in tests
  docker/mysql/export_common.sh
Labels: mysql

#1813 Fix Postgres 12+/Cloudberry concurrent backups.
  docker/cloudberry_tests/scripts/tests/backup_after_failed_backup_test.sh
  internal/databases/greenplum/extract_provider.go
  internal/databases/greenplum/extract_provider_with_spec.go
  internal/databases/greenplum/tars_to_extract_provider.go
  internal/databases/postgres/backup.go
  internal/databases/postgres/backup_new.go
  internal/databases/postgres/backup_push_handler.go
  internal/databases/postgres/bundle.go
  internal/databases/postgres/extract_provider.go
  internal/databases/postgres/extract_provider_with_spec.go
  internal/databases/postgres/tars_to_extract_provider.go
Labels: Greenplum

#1874 Add JournalInfo deletion logic
  cmd/mysql/delete.go
  docker-compose.yml
  docker/mysql_tests/scripts/base_tests/journals.sh
  internal/databases/mysql/backup_push_handler.go
  internal/journal.go
  internal/journal_test.go
Labels: mysql

#1842 Fixing [issue](https://github.com/wal-g/wal-g/issues/1809)
  internal/multistorage/stats/cache/cache_test.go
  internal/multistorage/stats/cache/file.go
Labels: postgres

#1894 add user to Redis connection
  cmd/redis/rdb_backup_fetch.go
  cmd/redis/rdb_backup_push.go
  docs/Redis.md
  go.mod
  go.sum
  internal/config/config.go
  internal/databases/redis/client/redis.go
  internal/tools/go.sum
  tests_func/config.go
  tests_func/helpers/redis.go
  tests_func/images/redis/config/wal-g-low-disk-usage.json
  tests_func/images/redis/config/wal-g.json
  tests_func/redis_steps.go
  tests_func/testcontext.go
  testtools/util.go
Labels: valkey
